<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="arm_base_link_length" value="0.1" />
    <xacro:property name="arm_base_link_width" value="0.1" />
    <xacro:property name="arm_base_link_height" value="0.02" />

    <xacro:property name="forearm_link_radius" value="0.02" />
    <xacro:property name="forearm_link_length" value="0.3" />

    <xacro:property name="hand_link_radius" value="0.02" />
    <xacro:property name="hand_link_length" value="0.3" />

    <!--link name="base_footprint"></link-->

    <link name="arm_base_link">
        <visual>
            <geometry>
                <box size="${arm_base_link_length} ${arm_base_link_width} ${arm_base_link_height}" />
            </geometry>
            <origin xyz="0 0 ${arm_base_link_height / 2.0}" rpy="0 0 0" />
            <material name="orange" />
        </visual>
        <collision>
            <geometry>
                <box size="${arm_base_link_length} ${arm_base_link_width} ${arm_base_link_height}" />
            </geometry>
            <origin xyz="0 0 ${arm_base_link_height / 2.0}" rpy="0 0 0" />
        </collision>
        <xacro:box_inertia m="10" x="${arm_base_link_length}" y="${arm_base_link_width}" z="${arm_base_link_height}"
                           o_xyz="0 0 ${arm_base_link_height / 2.0}" o_rpy="0 0 0" />
    </link>

    <link name="forearm_link">
        <visual>
            <geometry>
                <cylinder radius="${forearm_link_radius}" length="${forearm_link_length}" />
            </geometry>
            <origin xyz="0 0 ${forearm_link_length / 2.0}" rpy="0 0 0" />
            <material name="yellow" />
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${forearm_link_radius}" length="${forearm_link_length}" />
            </geometry>
            <origin xyz="0 0 ${forearm_link_length / 2.0}" rpy="0 0 0" />
        </collision>
        <xacro:cylinder_inertia m="0.3" r="${forearm_link_radius}" l="${forearm_link_length}"
                                o_xyz="0 0 ${forearm_link_length / 2.0}" o_rpy="0 0 0" />
    </link>

    <link name="hand_link">
        <visual>
            <geometry>
                <cylinder radius="${hand_link_radius}" length="${hand_link_length}" />
            </geometry>
            <origin xyz="0 0 ${hand_link_length / 2.0}" rpy="0 0 0" />
            <material name="orange" />
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${hand_link_radius}" length="${hand_link_length}" />
            </geometry>
            <origin xyz="0 0 ${hand_link_length / 2.0}" rpy="0 0 0" />
        </collision>
        <xacro:cylinder_inertia m="0.2" r="${hand_link_radius}" l="${hand_link_length}"
                                o_xyz="0 0 ${hand_link_length / 2.0}" o_rpy="0 0 0" />
    </link>

    
    <joint name="base_to_arm_joint" type="fixed">
        <parent link="base_link"/>
        <child link="arm_base_link" />
        <origin xyz="0 0 ${base_height}" rpy="0 0 0"/>
    </joint>

    <joint name="arm_to_forearm_joint" type="revolute">
        <parent link="arm_base_link" />
        <child link="forearm_link" />
        <origin xyz="0 0 ${arm_base_link_height}" rpy="0 0 0"/>
        <axis xyz="0 1 0" />
        <limit effort="100.0" lower="0" upper="1.57" velocity="100.0"/>
        <dynamics damping="0.3" friction="0.3"/>
        <safety_controller k_position="100" k_velocity="50" soft_lower_limit="-1.57" soft_upper_limit="1.57"/>
    </joint>
    
    <joint name="forearm_to_hand_joint" type="revolute">
        <parent link="forearm_link" />
        <child link="hand_link" />
        <origin xyz="0 0 ${forearm_link_length}" rpy="0 0 0"/>
        <axis xyz="0 1 0" />
        <limit effort="100.0" lower="0" upper="1.57" velocity="100.0"/>
        <dynamics damping="0.3" friction="0.3"/>
        <safety_controller k_position="100" k_velocity="50" soft_lower_limit="-1.57" soft_upper_limit="1.57"/>
    </joint>


</robot>